name: "Atlassian Confluence"
description: |
  Atlassian Confluence
version: 7.3.6.2
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://de.atlassian.com/software/confluence
