name: "GoCD Agent"
description: |
  The GoCD agent based on the original images
version: 0.0.1
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://github.com/EugenMayer/kontextwork-catalog/tree/master/templates/gocd-agent