app:
  image: eugenmayer/volume-persistence-test:0.0.2
  volumes:
    - /data
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
    io.rancher.container.pull_image: 'always'
