.catalog:
  name: "ApacheDS Ldap Server"
  version: "0.0.1"
  description: "LDAP Auth-Server based on ApacheDS"
  minimum_rancher_version: v0.63.0
  questions:
    - variable: "STORAGEPATH"
      label: "Data storage on the host"
      description: "Where should the ldap database be stored on the host"
      required: true
      type: "string"
    - variable: "CONFIGPATH"
      label: "Data where your bootstrap ist store"
      description: "Define where your ldap configuration bootstrap is stored"
      required: true
      type: "string"
    - variable: "BOOSTRAPFILE"
      label: "Path to a file to import"
      description: "Path to a file to import into you LDAP server on inital start"
      required: false
      type: "string"