.catalog:
  name: "GoCD agent"
  version: 0.0.1
  description: "The GoCD agent based on the original images"
  minimum_rancher_version: v0.63.0
  questions:
    - variable: "AGENT_SECRET_KEY"
      label: "Agent Secret Key"
      description: "The agent-key you configured on your gocd-server"
      required: true
      type: "password"
    - variable: "GO_SERVER"
      label: "GoCD Server Address"
      description: "how the agent should reach your gocd-server"
      required: true
      type: "password"
