.catalog:
  name: "GoCD Server"
  version: 0.0.2
  description: "The GoCD server based on the original images"
  minimum_rancher_version: v0.63.0
  questions:
    - variable: "GOSERVERSTORAGE"
      label: "Server storage"
      description: "Storage, either host path or name volume name"
      required: true
      type: "string"
    - variable: "GOCONFIGSTORAGE"
      label: "Config storage"
      description: "Storage, either host path or name volume name"
      required: true
      type: "string"
    - variable: "GOADDONSTORAGE"
      label: "Addong storage"
      description: "Storage, either host path or name volume name"
      required: true
      type: "string"
    - variable: "GOLIBSTORAGE"
      label: "Lib storage"
      description: "Storage, either host path or name volume name"
      required: true
      type: "string"
    - variable: "AGENT_SECRET_KEY"
      label: "Agent Secret Key"
      description: "The ky your agents need to provide to register with the gocd server"
      required: true
      type: "password"