gocd-agent:
  image: gocd/gocd-agent
  environment:
    AGENT_KEY: ${AGENT_SECRET_KEY}
    GO_SERVER: ${GO_SERVER}
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
  external_links:
  - ${GOCD_SERVICE}:db