.catalog:
  name: "GoCD agent"
  version: 0.0.2
  description: "The GoCD agent based on the original images"
  minimum_rancher_version: v0.63.0
  questions:
    - variable: "AGENT_SECRET_KEY"
      label: "Agent Secret Key"
      description: "The agent-key you configured on your gocd-server"
      required: true
      type: "password"
    - variable: "GO_SERVER"
      label: "Name of the define goserver-service url address"
      description: "Use 'go-server' if you have chosen a service below"
      default: 'go-server'
      required: true
      type: "string"
    - variable: "GOCD_SERVICE"
      label: "Service of the gocd-server"
      description: "Service of the go-server container used to contact the rancher server from the agent"
      required: true
      type: "service"